apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
  labels:
    app: node-app
    tier: backend
    version: v1
spec:
  selector:
    matchLabels:
      app: node-app
  replicas: 1
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-app
        image: localhost:32000/node-app
        ports:
        - containerPort: 8080
        env:
        - name: APP_NAME
          value: BAR
  